Warehouse/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Warehouse.Models
{
    public class LoginViewModel
    {
        [Display(Name = "User")]
        [Required(ErrorMessage = "{0} required!")]
        public string User { get; set; }

        [Display(Name = "Password")]
        [Required(ErrorMessage ="{0} required!")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name="Remind Me")]
        public bool RemindMe { get; set; }
    }
}

Warehouse/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Warehouse.Models;

namespace Warehouse.Controllers
{
    public class AccountController : Controller
    {
        // GET: Account
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(LoginViewModel login, string returnUrl)
        {
            if (!ModelState.IsValid) //if invalid login
            {
                return View(login);
            }

            //test
            var found = (login.User == "UserTest" && login.Password =="12345");

            //cookie authentication
            if (found)
            {
                FormsAuthentication.SetAuthCookie(login.User, login.RemindMe);

                if (Url.IsLocalUrl(returnUrl))
                {
                    return Redirect(returnUrl);
                }
                else
                {
                    RedirectToAction("Index", "Home");
                }
            }
            else
            {
                ModelState.AddModelError("", "Invalid Login, Try Again!");
            }
            return View(login);
        }
    }
}

Warehouse/Controllers/GraphicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Warehouse.Controllers
{
    public class GraphicController : Controller
    {
        // GET: Graphic
        [Authorize]
        public ActionResult MonthLoss()
        {
            return View();
        }
        // GET: Graphic
        [Authorize]
        public ActionResult CheckInCheckOut()
        {
            return View();
        }
    }
}

Warehouse/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Warehouse.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Warehouse/Controllers/OperationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Warehouse.Controllers
{
    public class OperationController : Controller
    {
        // GET: Operation
        [Authorize]
        public ActionResult ProductInput()
        {
            return View();
        }
        // GET: Operation
        [Authorize]
        public ActionResult ProductOutput()
        {
            return View();
        }
        // GET: Operation
        [Authorize]
        public ActionResult ProductLoss()
        {
            return View();
        }
        // GET: Operation
        [Authorize]
        public ActionResult Inventory()
        {
            return View();
        }
    }
}

Warehouse/Controllers/RegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Warehouse.Controllers
{
    public class RegistrationController : Controller
    {
        // GET: Registration
        [Authorize]
        public ActionResult ProductGroup()
        {
            return View();
        }
        // GET: Registration
        [Authorize]
        public ActionResult ProductBrand()
        {
            return View();
        }
        // GET: Registration
        [Authorize]
        public ActionResult Warehouse()
        {
            return View();
        }
        // GET: Registration
        [Authorize]
        public ActionResult MeasureUnit()
        {
            return View();
        }
        // GET: Registration
        [Authorize]
        public ActionResult Product()
        {
            return View();
        }
        // GET: Registration
        [Authorize]
        public ActionResult Country()
        {
            return View();
        }
        // GET: Registration
        [Authorize]
        public ActionResult State()
        {
            return View();
        }
        // GET: Registration
        [Authorize]
        public ActionResult City()
        {
            return View();
        }
        // GET: Registration
        [Authorize]
        public ActionResult Provider()
        {
            return View();
        }
        // GET: Registration
        [Authorize]
        public ActionResult UserProfile()
        {
            return View();
        }
        // GET: Registration
        [Authorize]
        public ActionResult User()
        {
            return View();
        }
    }
}

Warehouse/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Warehouse.Controllers
{
    public class ReportController : Controller
    {
        // GET: Report
        [Authorize]
        public ActionResult CurrentWarehouse()
        {
            return View();
        }
        // GET: Report
        [Authorize]
        public ActionResult Resupply()
        {
            return View();
        }
    }
}

Warehouse/Views/Graphic/CheckInCheckOut.cshtml
@{
    ViewBag.Title = "CheckInCheckOut";
}

<h2>CheckInCheckOut</h2>

Warehouse/Views/Graphic/MonthLoss.cshtml
@{
    ViewBag.Title = "MonthLoss";
}

<h2>MonthLoss</h2>

Warehouse/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Warehouse/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Warehouse/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Warehouse/Views/Operation/Inventory.cshtml
@{
    ViewBag.Title = "Inventory";
}

<h2>Inventory</h2>

Warehouse/Views/Operation/ProductInput.cshtml
@{
    ViewBag.Title = "ProductInput";
}

<h2>ProductInput</h2>

Warehouse/Views/Operation/ProductLoss.cshtml
@{
    ViewBag.Title = "ProductLoss";
}

<h2>ProductLoss</h2>

Warehouse/Views/Operation/ProductOutput.cshtml
@{
    ViewBag.Title = "ProductOutput";
}

<h2>ProductOutput</h2>

Warehouse/Views/Report/CurrentWarehouse.cshtml
@{
    ViewBag.Title = "CurrentWarehouse";
}

<h2>CurrentWarehouse</h2>

Warehouse/Views/Report/Resupply.cshtml
@{
    ViewBag.Title = "Resupply";
}

<h2>Resupply</h2>

Warehouse/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Warehouse Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Warehouse Application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <!--Registration menu-->
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Registration
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Product Groups", "ProductGroup", "Registration")</li>
                            <li>@Html.ActionLink("Brand Products", "ProductBrand", "Registration")</li>
                            <li>@Html.ActionLink("Warehouses", "Warehouse", "Registration")</li>
                            <li>@Html.ActionLink("Measure Unit", "MeasureUnit", "Registration")</li>
                            <li>@Html.ActionLink("Products", "Product", "Registration")</li>
                            <li class="nav-divider"></li>
                            <li>@Html.ActionLink("Countries", "Country", "Registration")</li>
                            <li>@Html.ActionLink("states", "State", "Registration")</li>
                            <li>@Html.ActionLink("Cities", "City", "Registration")</li>
                            <li>@Html.ActionLink("Providers", "Provider", "Registration")</li>
                            <li class="nav-divider"></li>
                            <li>@Html.ActionLink("Users Profile", "UserProfile", "Registration")</li>
                            <li>@Html.ActionLink("Users", "User", "Registration")</li>
                        </ul>
                    </li>

                    <!--Operations menu-->
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Operation
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Product Input", "ProductInput", "Operation")</li>
                            <li>@Html.ActionLink("Product Output", "ProductOutput", "Operation")</li>
                            <li>@Html.ActionLink("Product Loss", "ProductLoss", "Operation")</li>
                            <li>@Html.ActionLink("Inventory", "Inventory", "Operation")</li>
                        </ul>
                    </li>

                    <!--Report menu-->
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Report
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Current Warehouse", "CurrentWarehouse", "Report")</li>
                            <li>@Html.ActionLink("Resupply", "Resupply", "Report")</li>
                        </ul>
                    </li>

                    <!--Graphic menu-->
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Graphic
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Month Loss", "MonthLoss", "Graphic")</li>
                            <li>@Html.ActionLink("Check In and Check Out", "CheckInCheckOut", "Graphic")</li>
                        </ul>
                    </li>

                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Warehouse Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>